"use client";

import { Layers, Loader2, RefreshCw, Sparkles } from "lucide-react";
import type { ArchitectureRecommendation } from "@/lib/architect-engine";
import { ARCHITECT_FIELD_META } from "@/lib/architect-field-meta";
import { EditableArchitectField } from "@/components/architect/editable-architect-field";
import type { ArchitectOverrideContext } from "@/components/architect/use-architect-overrides";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/utils";

const OPENAI_FIELD_META = {
  pattern: {
    meaning: ARCHITECT_FIELD_META["architecture.pattern"].meaning,
    calculation:
      "Generated by OpenAI from the full use case text, architect brief, readiness scores, gaps, and telecom context.",
  },
  confidence: {
    meaning: ARCHITECT_FIELD_META["architecture.confidence"].meaning,
    calculation:
      "OpenAI confidence score (1–100) based on how well the use case and readiness data support this architecture.",
  },
  rationale: {
    meaning: ARCHITECT_FIELD_META["architecture.rationale"].meaning,
    calculation:
      "Narrative produced by OpenAI grounded in submitted content and assessment dimensions — not a fixed template.",
  },
  technologies: {
    meaning: ARCHITECT_FIELD_META["architecture.technologies"].meaning,
    calculation:
      "Technology stack suggested by OpenAI aligned to CGI's Microsoft-centric telecom practice.",
  },
};

export function ArchitectureCard({
  architecture,
  overrides,
  source = "rules",
  loading = false,
  error = null,
  model,
  generatedAt,
  stale = false,
  onRegenerate,
}: {
  architecture: ArchitectureRecommendation;
  overrides: ArchitectOverrideContext;
  source?: "openai" | "rules";
  loading?: boolean;
  error?: string | null;
  model?: string;
  generatedAt?: string;
  stale?: boolean;
  onRegenerate?: () => void;
}) {
  const meta = source === "openai" ? OPENAI_FIELD_META : ARCHITECT_FIELD_META;
  const patternMeta = source === "openai" ? meta.pattern : ARCHITECT_FIELD_META["architecture.pattern"];

  return (
    <div className="rounded-xl border border-primary/25 bg-gradient-to-br from-primary/5 to-card/80 p-6 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Layers className="h-5 w-5 text-primary" />
          <h3 className="font-semibold">Architecture Recommendation</h3>
          {source === "openai" ? (
            <Badge className="gap-1 border-primary/30 bg-primary/10 text-primary">
              <Sparkles className="h-3 w-3" />
              OpenAI
            </Badge>
          ) : (
            <Badge variant="outline">Rule-based</Badge>
          )}
          {stale && (
            <Badge variant="outline" className="border-amber-500/40 text-amber-600">
              Content changed — regenerate
            </Badge>
          )}
        </div>
        {onRegenerate && (
          <Button
            type="button"
            variant="outline"
            size="sm"
            disabled={loading}
            onClick={onRegenerate}
          >
            {loading ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <RefreshCw className="mr-2 h-4 w-4" />
            )}
            {loading ? "Analyzing…" : "Regenerate"}
          </Button>
        )}
      </div>

      {source === "openai" && model && generatedAt && (
        <p className="text-xs text-muted">
          Model: {model} · Generated {formatDate(generatedAt)}
        </p>
      )}

      {source === "rules" && !loading && !error && (
        <p className="text-xs text-muted">
          Set OPENAI_API_KEY in .env.local to generate recommendations from all use case text and readiness data.
        </p>
      )}

      {error && (
        <p className="text-sm text-destructive">
          {error}. Showing rule-based recommendation.
        </p>
      )}

      {loading && source === "rules" && (
        <p className="flex items-center gap-2 text-sm text-muted">
          <Loader2 className="h-4 w-4 animate-spin" />
          OpenAI is analyzing use case content…
        </p>
      )}

      <EditableArchitectField
        fieldKey="architecture.pattern"
        label="Pattern"
        value={architecture.pattern}
        meta={patternMeta}
        type="text"
        isOverridden={overrides.isOverridden("architecture.pattern")}
        overrideNote={overrides.getNote("architecture.pattern")}
        onSave={(v, note) => overrides.onSave("architecture.pattern", v, note)}
        onReset={() => overrides.onReset("architecture.pattern")}
      />

      <EditableArchitectField
        fieldKey="architecture.confidence"
        label="Confidence"
        value={architecture.confidence}
        displayValue={`${architecture.confidence}%`}
        meta={source === "openai" ? meta.confidence : ARCHITECT_FIELD_META["architecture.confidence"]}
        type="number"
        isOverridden={overrides.isOverridden("architecture.confidence")}
        overrideNote={overrides.getNote("architecture.confidence")}
        onSave={(v, note) => overrides.onSave("architecture.confidence", v, note)}
        onReset={() => overrides.onReset("architecture.confidence")}
      />

      <EditableArchitectField
        fieldKey="architecture.rationale"
        label="Rationale"
        value={architecture.rationale}
        meta={source === "openai" ? meta.rationale : ARCHITECT_FIELD_META["architecture.rationale"]}
        type="textarea"
        isOverridden={overrides.isOverridden("architecture.rationale")}
        overrideNote={overrides.getNote("architecture.rationale")}
        onSave={(v, note) => overrides.onSave("architecture.rationale", v, note)}
        onReset={() => overrides.onReset("architecture.rationale")}
      />

      <EditableArchitectField
        fieldKey="architecture.technologies"
        label="Technology stack"
        value={architecture.technologies.join(", ")}
        meta={source === "openai" ? meta.technologies : ARCHITECT_FIELD_META["architecture.technologies"]}
        type="textarea"
        isOverridden={overrides.isOverridden("architecture.technologies")}
        overrideNote={overrides.getNote("architecture.technologies")}
        onSave={(v, note) => overrides.onSave("architecture.technologies", v, note)}
        onReset={() => overrides.onReset("architecture.technologies")}
      />
    </div>
  );
}
