"use client";

import { Layers } from "lucide-react";
import type { ArchitectureRecommendation } from "@/lib/architect-engine";
import { ARCHITECT_FIELD_META } from "@/lib/architect-field-meta";
import { EditableArchitectField } from "@/components/architect/editable-architect-field";
import type { ArchitectOverrideContext } from "@/components/architect/use-architect-overrides";

const OPENAI_FIELD_META = {
  pattern: {
    meaning: ARCHITECT_FIELD_META["architecture.pattern"].meaning,
    calculation:
      "Generated by OpenAI from the business submission, readiness gaps, and telecom context.",
  },
  confidence: {
    meaning: ARCHITECT_FIELD_META["architecture.confidence"].meaning,
    calculation:
      "OpenAI confidence score (1–100) based on how well the use case supports this architecture.",
  },
  rationale: {
    meaning: ARCHITECT_FIELD_META["architecture.rationale"].meaning,
    calculation:
      "Narrative produced by OpenAI grounded in submitted content — not a fixed template.",
  },
  technologies: {
    meaning: ARCHITECT_FIELD_META["architecture.technologies"].meaning,
    calculation:
      "Technology stack suggested by OpenAI aligned to CGI's Microsoft-centric telecom practice.",
  },
};

export function ArchitectureCard({
  architecture,
  overrides,
  source = "rules",
}: {
  architecture: ArchitectureRecommendation;
  overrides: ArchitectOverrideContext;
  source?: "openai" | "rules";
}) {
  const meta = source === "openai" ? OPENAI_FIELD_META : ARCHITECT_FIELD_META;
  const patternMeta = source === "openai" ? meta.pattern : ARCHITECT_FIELD_META["architecture.pattern"];

  return (
    <div className="rounded-xl border border-primary/25 bg-gradient-to-br from-primary/5 to-card/80 p-6 space-y-4">
      <div className="flex items-center gap-2">
        <Layers className="h-5 w-5 text-primary" />
        <h3 className="font-semibold">Architecture Recommendation</h3>
      </div>

      <EditableArchitectField
        fieldKey="architecture.pattern"
        label="Pattern"
        value={architecture.pattern}
        meta={patternMeta}
        type="text"
        isOverridden={overrides.isOverridden("architecture.pattern")}
        overrideNote={overrides.getNote("architecture.pattern")}
        onSave={(v, note) => overrides.onSave("architecture.pattern", v, note)}
        onReset={() => overrides.onReset("architecture.pattern")}
      />

      <EditableArchitectField
        fieldKey="architecture.confidence"
        label="Confidence"
        value={architecture.confidence}
        displayValue={`${architecture.confidence}%`}
        meta={source === "openai" ? meta.confidence : ARCHITECT_FIELD_META["architecture.confidence"]}
        type="number"
        isOverridden={overrides.isOverridden("architecture.confidence")}
        overrideNote={overrides.getNote("architecture.confidence")}
        onSave={(v, note) => overrides.onSave("architecture.confidence", v, note)}
        onReset={() => overrides.onReset("architecture.confidence")}
      />

      <EditableArchitectField
        fieldKey="architecture.rationale"
        label="Rationale"
        value={architecture.rationale}
        meta={source === "openai" ? meta.rationale : ARCHITECT_FIELD_META["architecture.rationale"]}
        type="textarea"
        isOverridden={overrides.isOverridden("architecture.rationale")}
        overrideNote={overrides.getNote("architecture.rationale")}
        onSave={(v, note) => overrides.onSave("architecture.rationale", v, note)}
        onReset={() => overrides.onReset("architecture.rationale")}
      />

      <EditableArchitectField
        fieldKey="architecture.technologies"
        label="Technology stack"
        value={architecture.technologies.join(", ")}
        meta={source === "openai" ? meta.technologies : ARCHITECT_FIELD_META["architecture.technologies"]}
        type="textarea"
        isOverridden={overrides.isOverridden("architecture.technologies")}
        overrideNote={overrides.getNote("architecture.technologies")}
        onSave={(v, note) => overrides.onSave("architecture.technologies", v, note)}
        onReset={() => overrides.onReset("architecture.technologies")}
      />
    </div>
  );
}
